name: TSC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: server dir
      run: cd server
    - name: yarn install
      run: yarn install
    - name: tsc
      uses: icrawl/action-tsc@v1
      with:
        project: server
